# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Calculate classification probabilities for binary Polya tree classification problem with a single feature (for multiple candidate values of smoothing parameter)
#'
#' @param x1       training sample from group 1
#' @param x0       training sample from group 0
#' @param xnew     new data point
#' @param cval     candidate values of smoothing parameter
#' @param m        mean of centering Gaussian distribution
#' @param s        sd of centering Gaussian distribution
#' @param DOWN     Leave this number as 0
#' @param UP       Leave this number as 1
#' @param depth       Leave this number as 0
#' @param maxdepth    Maximum depth to truncate the tree. Default is 10.
#'
#' @return         Classification probability
#'
#' @export
#' @rawNamespace useDynLib(VaDA)
#'
#' @examples
#' samp1 <- rnorm(50,4,1)
#' samp0 <- rt(40,3)
#' xtest <- rt(1,3)
#' DividePredCpp(x1 = samp1, x0 = samp0, xnew = xtest, cval = 1, m = mean(c(samp1,samp0)), s = sd(c(samp1,samp0)))
NULL

#' @title Calculating differences between two sets
#'
#' @param x        vector of elements in first set
#' @param y        vector of elements in second set
#'
#' @return         Vector of set differences
#'
#' @export
#' @rawNamespace useDynLib(VaDA)
#'
#' @examples
#' x <- c(1,3,4,5,8); y <- c(1, 2, 4, 5, 8)
#' arma_setdiff(x,y)
arma_setdiff <- function(x, y) {
    .Call('_VaDA_arma_setdiff', PACKAGE = 'VaDA', x, y)
}

#' @title Applies the expit (inverse logit) function.
#'
#' @param v        vector of input
#'
#' @return         Vector of output
#'
#' @export
#' @rawNamespace useDynLib(VaDA)
#'
#' @examples
#' x <- rt(100,1)
#' expit(x)
expit <- function(v) {
    .Call('_VaDA_expit', PACKAGE = 'VaDA', v)
}

#' @title Applies the epsilon function in Yu et. al. (2018).
#'
#' @param v        vector of input
#'
#' @return         Vector of output
#'
#' @export
#' @rawNamespace useDynLib(VaDA)
#'
#' @examples
#' x <- rt(1,10)
#' epsilonC(x)
epsilonC <- function(v) {
    .Call('_VaDA_epsilonC', PACKAGE = 'VaDA', v)
}

#' @title Fit the VLDA model in Yu et. al. (2018).
#'
#' @param vy        Class labels of training sample
#' @param mX        Variables of training sample
#' @param mXtest        Variables of testing sample (for prediction)
#' @param r        tuning parameter 1 for penalty  on log likelihood
#' @param kappa        tuning parameter 2 for penalty  on log likelihood
#'
#' @return         List containing variable selection probabilities, classification probabilitiew, likelihood ratio statistics and classification results
#'
#' @export
#' @rawNamespace useDynLib(VaDA)
#'
#' @examples
#' data(LIHCtoy)
#' X <- as.matrix(X)
#' resVLDA <- VLDA(vy = y[1:90], mX = X[1:90,], mXtest = X[91:109,], r = 0.98, kappa = (1/7))
#' resVLDA
VLDA <- function(vy, mX, mXtest, r, kappa) {
    .Call('_VaDA_VLDA', PACKAGE = 'VaDA', vy, mX, mXtest, r, kappa)
}

#' @title Fit the VQDA model in Yu et. al. (2018).
#'
#' @param vy        Class labels of training sample
#' @param mX        Variables of training sample
#' @param mXtest        Variables of testing sample (for prediction)
#' @param r        tuning parameter 1 for penalty  on log likelihood
#' @param kappa        tuning parameter 2 for penalty  on log likelihood
#'
#' @return         List containing variable selection probabilities, classification probabilitiew, likelihood ratio statistics and classification results
#'
#' @export
#' @rawNamespace useDynLib(VaDA)
#'
#' @examples
#' data(LIHCtoy)
#' X <- as.matrix(X)
#' resVQDA <- VQDA(vy = y[1:90], mX = X[1:90,], mXtest = X[91:109,], r = 0.98, kappa = (1/7))
#' resVQDA
VQDA <- function(vy, mX, mXtest, r, kappa) {
    .Call('_VaDA_VQDA', PACKAGE = 'VaDA', vy, mX, mXtest, r, kappa)
}

#' @title Calculate classification probabilities for binary Polya tree classification problem with a single feature
#'
#' @param x1       training sample from group 1
#' @param x0       training sample from group 0
#' @param xnew     new data point
#' @param cval     smoothing parameter
#' @param m        mean of centering Gaussian distribution
#' @param s        sd of centering Gaussian distribution
#' @param DOWN     Leave this number as 0
#' @param UP       Leave this number as 1
#' @param depth       Leave this number as 0
#' @param maxdepth    Maximum depth to truncate the tree. Default is 10.
#'
#' @return         Classification probability
#'
#' @export
#' @rawNamespace useDynLib(VaDA)
#'
#' @examples
#' samp1 <- rnorm(50,4,1)
#' samp0 <- rt(40,3)
#' xtest <- rt(1,3)
#' DividePredCpp(x1 = samp1, x0 = samp0, xnew = xtest, cval = 1, m = mean(c(samp1,samp0)), s = sd(c(samp1,samp0)))
DividePredCpp <- function(x1, x0, xnew, cval, m, s, DOWN = 0, UP = 1, depth = 0L, maxdepth = 10L) {
    .Call('_VaDA_DividePredCpp', PACKAGE = 'VaDA', x1, x0, xnew, cval, m, s, DOWN, UP, depth, maxdepth)
}

#' @title Calculate classification probabilities for binary Polya tree classification problem with multiple features
#'
#' @param xtrain1  training sample from group 1 (matrix)
#' @param xtrain0  training sample from group 0 (matrix)
#' @param xtest    a single new data point (vector)
#' @param cval     smoothing parameters
#' @param omega    vector of variable selection weights
#' @param ay        hyperparameter 1 of beta prior
#' @param by        hyperparameter 2 of beta prior
#' @param maxdepth    Maximum depth to truncate the tree. Default is 10.
#'
#' @return         Classification probability
#'
#' @export
#' @rawNamespace useDynLib(VaDA)
#'
PredCpp <- function(xtrain1, xtrain0, xtest, cval, omega, ay, by, maxdepth = 10L) {
    .Call('_VaDA_PredCpp', PACKAGE = 'VaDA', xtrain1, xtrain0, xtest, cval, omega, ay, by, maxdepth)
}

#' @title Performs a two-sample Bayesian nonparametric Polya tree test between two independent univariate samples
#'
#' @param x1  training sample from group 1
#' @param x0  training sample from group 0
#' @param cval     smoothing parameter
#' @param m        mean of centering Gaussian distribution
#' @param s        sd of centering Gaussian distribution
#' @param DOWN     Leave this number as 0
#' @param UP       Leave this number as 1
#' @param depth       Leave this number as 0
#' @param maxdepth    Maximum depth to truncate the tree. Default is 10.
#'
#' @return         log Bayes factor
#'
#' @export
#' @rawNamespace useDynLib(VaDA)
#'
TREECpp <- function(x1, x0, cval, m, s, DOWN, UP, depth, maxdepth = 10L) {
    .Call('_VaDA_TREECpp', PACKAGE = 'VaDA', x1, x0, cval, m, s, DOWN, UP, depth, maxdepth)
}

#' @title Fits the VNPDA model with a distinct smoothing parameter for each variable
#'
#' @param xtrain  Variables of training sample (matrix)
#' @param ytrain  Group labels of training sample
#' @param Xtest   Variables of testing sample for classification (matrix)
#' @param cval    Vector of smoothing parameter values
#' @param ay      Hyparameter 1 of Beta prior for rho_y
#' @param by      Hyparameter 2 of Beta prior for rho_y
#' @param ag      Hyparameter 1 of Beta prior for rho_gamma
#' @param bg      Hyparameter 2 of Beta prior for rho_gamma
#' @param maxdepth  Maximum depth to truncate the tree. Default is 10.
#'
#' @return         List of variable selection and classification results
#'
#' @export
#' @rawNamespace useDynLib(VaDA)
#'
VNPDA <- function(xtrain, ytrain, Xtest, cval, ay, by, ag, bg, maxdepth = 10L) {
    .Call('_VaDA_VNPDA', PACKAGE = 'VaDA', xtrain, ytrain, Xtest, cval, ay, by, ag, bg, maxdepth)
}

#' @title Introduces random perturbation to a set of variables
#'
#' @param Z  matrix of values to be perturbed
#'
#' @return         perturbed matrix
#'
#' @export
#' @rawNamespace useDynLib(VaDA)
#'
PerturbCpp <- function(Z) {
    .Call('_VaDA_PerturbCpp', PACKAGE = 'VaDA', Z)
}

#' @title Sampling with replacement from a vector of numbers
#'
#' @param x  Vector of elements to sample from
#' @param numObs  Number of draws required
#' @param weights  Sampling weights
#'
#' @return        vector of draws
#'
#' @export
#' @rawNamespace useDynLib(VaDA)
#'
ArmaSample <- function(x, numObs, weights) {
    .Call('_VaDA_ArmaSample', PACKAGE = 'VaDA', x, numObs, weights)
}

#' @title Sampling from a mixture of univariate normals
#'
#' @param N        Number of rows in output
#' @param p        Number of columns in outout
#' @param indices  Recommended to be sequence from 1 to p
#' @param weights  Sampling probabilities
#' @param meanVec  Vector of Gaussian means
#' @param sdVec    Vector of Gaussian SDs
#'
#' @return        matrix N by p of draws
#'
#' @export
#' @rawNamespace useDynLib(VaDA)
#'
SampleMixNorm <- function(N, p, indices, weights, meanVec, sdVec) {
    .Call('_VaDA_SampleMixNorm', PACKAGE = 'VaDA', N, p, indices, weights, meanVec, sdVec)
}

#' @title Calls the two-sample KS test function for two univariate samples in R
#'
#' @param x       Sample 1
#' @param y       Sample 0
#'
#' @return        KS test p-value
#'
#' @export
#' @rawNamespace useDynLib(VaDA)
#'
simpleKS <- function(x, y) {
    .Call('_VaDA_simpleKS', PACKAGE = 'VaDA', x, y)
}

#' @title Calls the two-sample KS test function for two multivariate samples in R
#'
#' @param X       Sample
#' @param y       Group labels (1 or 0)
#'
#' @return        KS test p-value
#'
#' @export
#' @rawNamespace useDynLib(VaDA)
#'
KSmatrix <- function(X, y) {
    .Call('_VaDA_KSmatrix', PACKAGE = 'VaDA', X, y)
}

#' @title Performs a two-sample Bayesian nonparametric Polya tree test between two independent univariate samples (for multiple candidate values of smoothing paramater)
#'
#' @param x1  training sample from group 1
#' @param x0  training sample from group 0
#' @param cval     candidate value for smoothing parameter (vector)
#' @param m        mean of centering Gaussian distribution
#' @param s        sd of centering Gaussian distribution
#' @param DOWN     Leave this number as 0
#' @param UP       Leave this number as 1
#' @param depth       Leave this number as 0
#' @param maxdepth    Maximum depth to truncate the tree. Default is 10.
#'
#' @return         log Bayes factor
#'
#' @export
#' @rawNamespace useDynLib(VaDA)
#'
TREECppCVselect <- function(x1, x0, cval, m, s, DOWN = 0.0, UP = 1.0, depth = 0.0, maxdepth = 10L) {
    .Call('_VaDA_TREECppCVselect', PACKAGE = 'VaDA', x1, x0, cval, m, s, DOWN, UP, depth, maxdepth)
}

#' @title Calculate classification probabilities for binary Polya tree classification problem with multiple features (for mutiple candidate values of smoothing parameter)
#'
#' @param xtrain1  training sample from group 1 (matrix)
#' @param xtrain0  training sample from group 0 (matrix)
#' @param xtest    a single new data point (vector)
#' @param cval     candidate values for smoothing parameter (matrix)
#' @param omega    vector of variable selection weights
#' @param ay        hyperparameter 1 of beta prior
#' @param by        hyperparameter 2 of beta prior
#' @param maxdepth    Maximum depth to truncate the tree. Default is 10.
#'
#' @return         Classification probability
#'
#' @export
#' @rawNamespace useDynLib(VaDA)
#'
PredCppCVselect <- function(xtrain1, xtrain0, xtest, cval, omega, ay, by, maxdepth = 10L) {
    .Call('_VaDA_PredCppCVselect', PACKAGE = 'VaDA', xtrain1, xtrain0, xtest, cval, omega, ay, by, maxdepth)
}

#' @title Fits the VNPDA model for a set of candidate value of smoothing parameters for each variable and returns the optimal smoothing parameter value
#'
#' @param xtrain  Variables of training sample (matrix)
#' @param ytrain  Group labels of training sample
#' @param Xtest   Variables of testing sample for classification (matrix)
#' @param cval     candidate values for smoothing parameter (matrix)
#' @param ay      Hyparameter 1 of Beta prior for rho_y
#' @param by      Hyparameter 2 of Beta prior for rho_y
#' @param ag      Hyparameter 1 of Beta prior for rho_gamma
#' @param bg      Hyparameter 2 of Beta prior for rho_gamma
#' @param maxdepth  Maximum depth to truncate the tree. Default is 10.
#'
#' @return         Optimal smoothing parameter settings
#'
#' @export
#' @rawNamespace useDynLib(VaDA)
#'
CVselectC <- function(xtrain, ytrain, cval, ay, by, ag, bg, maxdepth = 10L) {
    .Call('_VaDA_CVselectC', PACKAGE = 'VaDA', xtrain, ytrain, cval, ay, by, ag, bg, maxdepth)
}

