# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Calculating differences between two sets
#'
#' @param x        vector of elements in first set
#' @param y        vector of elements in second set
#'
#' @return         Vector of set differences
#'
#' @export
#' @rawNamespace useDynLib(VaDA)
#'
#' @examples
#' x <- c(1,3,4,5,8); y <- c(1, 2, 4, 5, 8)
#' arma_setdiff(x,y)
arma_setdiff <- function(x, y) {
    .Call('_VaDA_arma_setdiff', PACKAGE = 'VaDA', x, y)
}

#' @title Applies the expit (inverse logit) function.
#'
#' @param v        vector of input
#'
#' @return         Vector of output
#'
#' @export
#' @rawNamespace useDynLib(VaDA)
#'
#' @examples
#' x <- rt(100,1)
#' expit(x)
expit <- function(v) {
    .Call('_VaDA_expit', PACKAGE = 'VaDA', v)
}

#' @title Applies the epsilon function in Yu et. al. (2018).
#'
#' @param v        vector of input
#'
#' @return         Vector of output
#'
#' @export
#' @rawNamespace useDynLib(VaDA)
#'
#' @examples
#' x <- rt(1,10)
#' epsilonC(x)
epsilonC <- function(v) {
    .Call('_VaDA_epsilonC', PACKAGE = 'VaDA', v)
}

#' @title Fit the VLDA model in Yu et. al. (2018).
#'
#' @param vy        Class labels of training sample
#' @param mX        Variables of training sample
#' @param mXtest        Variables of testing sample (for prediction)
#' @param r        tuning parameter 1 for penalty  on log likelihood
#' @param kappa        tuning parameter 2 for penalty  on log likelihood
#'
#' @return         List containing variable selection probabilities, classification probabilitiew, likelihood ratio statistics and classification results
#'
#' @export
#' @rawNamespace useDynLib(VaDA)
#'
#' @examples
#' data(LIHCtoy)
#' X <- as.matrix(X)
#' resVLDA <- VLDA(vy = y[1:90], mX = X[1:90,], mXtest = X[91:109,], r = 0.98, kappa = (1/7))
#' resVLDA
VLDA <- function(vy, mX, mXtest, r, kappa) {
    .Call('_VaDA_VLDA', PACKAGE = 'VaDA', vy, mX, mXtest, r, kappa)
}

#' @title Fit the VQDA model in Yu et. al. (2018).
#'
#' @param vy        Class labels of training sample
#' @param mX        Variables of training sample
#' @param mXtest        Variables of testing sample (for prediction)
#' @param r        tuning parameter 1 for penalty  on log likelihood
#' @param kappa        tuning parameter 2 for penalty  on log likelihood
#'
#' @return         List containing variable selection probabilities, classification probabilitiew, likelihood ratio statistics and classification results
#'
#' @export
#' @rawNamespace useDynLib(VaDA)
#'
#' @examples
#' data(LIHCtoy)
#' X <- as.matrix(X)
#' resVQDA <- VQDA(vy = y[1:90], mX = X[1:90,], mXtest = X[91:109,], r = 0.98, kappa = (1/7))
#' resVQDA
VQDA <- function(vy, mX, mXtest, r, kappa) {
    .Call('_VaDA_VQDA', PACKAGE = 'VaDA', vy, mX, mXtest, r, kappa)
}

